[2022-09-22 09:00:15,586] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_customized.local_to_gcs_task manual__2022-09-22T09:00:10.619280+00:00 [queued]>
[2022-09-22 09:00:15,593] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_customized.local_to_gcs_task manual__2022-09-22T09:00:10.619280+00:00 [queued]>
[2022-09-22 09:00:15,593] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-09-22 09:00:15,593] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-09-22 09:00:15,593] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-09-22 09:00:15,601] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-09-22 09:00:10.619280+00:00
[2022-09-22 09:00:15,605] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2022-09-22 09:00:15,607] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_customized', 'local_to_gcs_task', 'manual__2022-09-22T09:00:10.619280+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_customized.py', '--cfg-path', '/tmp/tmpy64p6itl', '--error-file', '/tmp/tmpuoo7vxc7']
[2022-09-22 09:00:15,607] {standard_task_runner.py:77} INFO - Job 26: Subtask local_to_gcs_task
[2022-09-22 09:00:15,641] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_customized.local_to_gcs_task manual__2022-09-22T09:00:10.619280+00:00 [running]> on host 9ab9fcef6297
[2022-09-22 09:00:15,679] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_customized
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-09-22T09:00:10.619280+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-09-22T09:00:10.619280+00:00
[2022-09-22 09:00:16,287] {python.py:175} INFO - Done. Returned value was: None
[2022-09-22 09:00:16,295] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag_customized, task_id=local_to_gcs_task, execution_date=20220922T090010, start_date=20220922T090015, end_date=20220922T090016
[2022-09-22 09:00:16,341] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-09-22 09:00:16,360] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
